name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build jekyll/builder
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod a+w /srv/jekyll/Gemfile.lock && chmod 777 /srv/jekyll && JEKYLL_ENV=production jekyll build --future --config ./_config.yml"
    - name: Commit to Main
      uses: github-actions-x/commit@v2.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: '[ Generate Jekyll Website ]'
        force-add: 'true'
    # - name: Deploy to gh-pages
    #   uses: docker://peaceiris/gh-pages:v2.5.0
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     push-branch: 'gh-pages'
    #     publish_dir: ./_site
    #   env:
    #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    #     PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    #     PUBLISH_BRANCH: gh-pages
    #     PUBLISH_DIR: ./_site
#   build-and-deploy:
#     strategy:
#       matrix:
#         ruby: [2.4.1]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout üõéÔ∏è
#         uses: actions/checkout@v2.3.1

#       - name: Install and Build üîß # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
#         run: JEKYLL_ENV=production bundle exec jekyll build --config ./_config.yml

#       - name: Deploy üöÄ
#         uses: JamesIves/github-pages-deploy-action@4.1.1
#         with:
#           branch: gh-pages # The branch the action should deploy to.
#           folder: build # The folder the action should deploy.
